tasks:
  - before: npm install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
    #onOpen: open-browser

vscode:
  extensions:
    - mgmcdermott.vscode-language-babel